import {useEffect,useState} from 'react';
import {ArrowUpRight,GitBranch,Star,GitCommitHorizontal} from 'lucide-react';
import snapshot from '../data/github-snapshot.json';
import {socials} from '../data/socials';
export default function BuildLog(){const[repos,setRepos]=useState(snapshot.repositories);const[live,setLive]=useState(false);const[events,setEvents]=useState(snapshot.events);
useEffect(()=>{const controller=new AbortController();fetch('https://api.github.com/users/Devparth7-coder/repos?per_page=100',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{if(Array.isArray(data)){const selected=data.filter((r:{name:string})=>snapshot.repositories.some(s=>s.name===r.name));if(selected.length===10){setRepos(selected);setLive(true)}}}).catch(()=>{});fetch('https://api.github.com/users/Devparth7-coder/events/public?per_page=30',{signal:controller.signal}).then(r=>r.ok?r.json():Promise.reject()).then(data=>{if(Array.isArray(data))setEvents(data.filter((e:{repo:{name:string}})=>snapshot.repositories.some(r=>e.repo.name===`Devparth7-coder/${r.name}`)).slice(0,4))}).catch(()=>{});return()=>controller.abort()},[]);
const langs=Object.entries(snapshot.languages).sort((a,b)=>b[1]-a[1]);const sum=langs.reduce((s,l)=>s+l[1],0);const shown=langs.slice(0,4);const last=Array.from(repos).sort((a,b)=>b.pushed_at.localeCompare(a.pushed_at)).slice(0,3);
return <section id="build-log" className="section container reveal"><div className="section-heading"><div><span className="eyebrow"><span>07 /</span> IN THE OPEN</span><h2>BUILD LOG<span className="accent">.</span></h2></div><a href={socials.github} target="_blank" rel="noreferrer" className="text-link">Explore full GitHub <ArrowUpRight size={17}/></a></div><div className="build-grid"><div className="contribution-panel"><div className="panel-head"><span className="mono"><GitBranch size={15}/> Devparth7-coder</span><span className="snapshot-label mono">GITHUB / SNAPSHOT</span></div><div className="calendar-months mono"><span>SEP</span><span>DEC</span><span>MAR</span><span>JUN</span><span>SEP</span></div><div className="contribution-grid" role="img" aria-label="Actual GitHub contribution calendar, September 2025 to September 2026">{snapshot.contributions.map(d=><span key={d.date} data-level={d.level} title={`${d.date}: ${d.label}`}/>)}</div><div className="calendar-footer"><span>Small commits. Compounding progress.</span><div className="legend mono">LESS {[0,1,2,3,4].map(i=><span key={i} data-level={i}/>)} MORE</div></div><div className="language-bar" aria-label="Language distribution by bytes in the ten selected repositories">{shown.map(([n,v],i)=><span key={n} style={{width:`${v/sum*100}%`,background:`var(--lang-${i})`}} title={`${n}: ${(v/sum*100).toFixed(1)}%`}/>)}<span style={{flex:1,background:'#303b29'}}/></div><div className="language-labels mono">{shown.map(([n,v],i)=><span key={n}><i style={{background:`var(--lang-${i})`}}/>{n} {(v/sum*100).toFixed(1)}%</span>)}<span>Other {(100-shown.reduce((s,l)=>s+l[1]/sum*100,0)).toFixed(1)}%</span></div><small>Calendar & language snapshot: 08 Sep 2026. Language bytes across the 10 selected repositories.</small></div><div className="repo-panel"><div className="panel-head"><span className="mono">SELECTED REPOSITORIES</span><span className="mono accent">{live?'LIVE API':'SAVED SNAPSHOT'}</span></div>{last.map(r=><a key={r.name} className="repo-row" href={r.html_url} target="_blank" rel="noreferrer"><GitBranch size={16}/><div><strong>{r.name}</strong><span>{r.language} <b>·</b> Updated {new Date(r.pushed_at).toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</span></div><span className="repo-stars"><Star size={12}/>{r.stargazers_count}</span><ArrowUpRight size={15}/></a>)}<div className="activity"><span className="eyebrow">RECENT / CURATED ACTIVITY</span>{events.length?events.slice(0,2).map(e=><a href={`https://github.com/${e.repo.name}`} key={e.id} target="_blank" rel="noreferrer"><GitCommitHorizontal size={16}/><span>{e.type.replace('Event','')} · {e.repo.name.split('/')[1]}</span><time>{new Date(e.created_at).toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</time></a>):<p>No recent public events for the selected projects. Repository updates are shown above.</p>}</div></div></div></section>
}
